include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - avoid_redundant_argument_values
    - unnecessary_lambdas

formatter:
  page_width: 100